[package]
name = "confab"
version = "0.1.0-alpha"
edition = "2021"
rust-version = "1.64"
description = "Asynchronous line-oriented interactive TCP client"
authors = ["John Thorvald Wodder II <confab@varonathe.org>"]
repository = "https://github.com/jwodder/confab"
documentation = "https://github.com/jwodder/confab"
license = "MIT"
keywords = ["tcp", "client", "chat"]
categories = ["command-line-utilities", "network-programming"]
exclude = ["/.*"]

[dependencies]
anyhow = "1.0.70"
bytes = "1.4.0"
chrono = "0.4.24"
clap = { version = "4.2.1", default-features = false, features = ["derive", "error-context", "help", "std", "suggestions", "usage", "wrap_help"] }
crossterm = "0.26.1"
futures = "0.3.28"
itertools = "0.10.5"
native-tls = "0.2.11"
openssl = { version = "0.10.49", optional = true }
pin-project = "1.0.12"
rustyline-async = "0.3.1"
tokio = { version = "1.26.0", features = ["macros", "net", "rt", "rt-multi-thread"] }
tokio-native-tls = "0.3.1"
tokio-util = { version = "0.7.7", features = ["codec"] }
unicode-general-category = "0.6.0"

[dev-dependencies]
expectrl = { version = "0.7.0", features = ["async"] }
rstest = { version = "0.17.0", default-features = false }
tokio = { version = "1.26.0", features = ["io-util", "sync", "time"] }
tokio-stream = { version = "0.1.12", features = ["time"] }

[features]
vendored-openssl = ["openssl/vendored"]

[profile.release]
lto = true
strip = true
