[package]
name = "netlion"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.66"
clap = { version = "4.0.26", default-features = false, features = ["derive", "error-context", "help", "std", "suggestions", "usage", "wrap_help"] }
futures = "0.3.25"
rustyline-async = "0.2.6"
tokio = { version = "1.22.0", features = ["rt", "rt-multi-thread", "macros", "net"] }
tokio-util = { version = "0.7.4", features = ["codec"] }

[dev-dependencies]
