[graph]
targets = []
all-features = true
no-default-features = false

[advisories]
version = 2
yanked = "deny"
ignore = [
    "RUSTSEC-2024-0384",  # Can't do anything about this
    "RUSTSEC-2025-0007",  # Don't care
]

[bans]
multiple-versions = "allow"
wildcards = "allow"

[licenses]
version = 2
allow = [
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "MIT",
    "OpenSSL",
    "Unicode-3.0",
    "Unicode-DFS-2016",
    "Unlicense",
]
unused-allowed-license = "allow"

[[licenses.clarify]]
name = "ring"
expression = "ISC AND OpenSSL AND MIT"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 }
]

[sources]
unknown-git = "deny"
unknown-registry = "deny"
