[graph]
targets = []
all-features = true
no-default-features = false

[advisories]
db-path = "~/.cargo/advisory-db"
notice = "warn"
unmaintained = "warn"
vulnerability = "deny"
yanked = "deny"

[bans]
multiple-versions = "allow"
wildcards = "allow"

[licenses]
allow = []
allow-osi-fsf-free = "either"
copyleft = "deny"
default = "deny"
unlicensed = "deny"

[[licenses.clarify]]
name = "ring"
expression = "ISC AND OpenSSL AND MIT"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 }
]

[sources]
unknown-git = "deny"
unknown-registry = "deny"
