[workspace]
members = ["cargo:."]

[dist]
cargo-dist-version = "0.25.1"
ci = "github"
include = ["THIRDPARTY.toml", "doc/confab.1"]
install-updater = false
installers = ["shell", "powershell"]
pr-run-mode = "upload"
targets = ["aarch64-apple-darwin", "x86_64-apple-darwin", "x86_64-unknown-linux-gnu", "x86_64-unknown-linux-musl", "x86_64-pc-windows-msvc"]
install-path = "CARGO_HOME"
