[workspace]
members = ["cargo:."]

[dist]
cargo-dist-version = "0.28.0"
ci = "github"
include = ["THIRDPARTY.toml", "doc/confab.1"]
install-path = "CARGO_HOME"
install-updater = false
installers = ["shell", "powershell"]
pr-run-mode = "upload"
targets = [
    "aarch64-apple-darwin",
    "aarch64-unknown-linux-gnu",
    "x86_64-apple-darwin",
    "x86_64-pc-windows-msvc",
    "x86_64-unknown-linux-gnu",
    "x86_64-unknown-linux-musl",
]

[dist.github-custom-runners]
global = "ubuntu-22.04"

[dist.github-custom-runners.aarch64-unknown-linux-gnu]
runner = "ubuntu-22.04"

[dist.github-custom-runners.x86_64-unknown-linux-gnu]
runner = "ubuntu-22.04"

[dist.github-custom-runners.x86_64-unknown-linux-musl]
runner = "ubuntu-22.04"

[dist.github-custom-runners.x86_64-pc-windows-msvc]
runner = "windows-2022"
